content/_/_index.md
Here are some minor improvements and fixes here and there.
=> Minor improvements

content/_index.md
There is no (syntactic) auto-usage or `Default` for arrays; you would need to write `[T::default(); n]` to get the effect, and then only if `T: Copy`.
=> Fix incorrect symbol description.

content/_index.md
Cargo aliases are not that easy to find, I think it’s handy to have it here.
This list comes from https://github.com/rust-lang/cargo/pull/6218/
=> Add cargo aliases

content/_index.md
In these RFCs, great details and example are given about the right way to do
documentation. I’m not sure if this is worth being detailed on
cheats.rs, but a link is a way as good as another to find these
documents.
In particular, these RFC are way more detailed than the Reference book.
See Rust-lang [Contributing.md][RContrib] for a proof that RFC1574 is used for std.
[RContrib]: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#writing-documentation
=> Add references to RFCs defining good documentation practices

content/_index.md
This addresses #29 by adding a new section for common format string flags
along with some examples.
=> Add section for format strings

content/_index.md
There are more (in various degrees of stability, like RLS or llvm tools)
but since clippy and rustfmt are already mentioned I chose to start with
these two.
=> Add section on rustup components

content/_index.md
First of all, thank you for the incredible cheat sheet! 
I found this little issue: 
Exclusive range pattern syntax (`1..5`) is experimental. `1...5` is used in the book, but afaik it will be deprecated in favor for `1..=5`. Later works in both, stable and nightly, without a warning.
=> Fix range pattern in match

content/_index.md
It seems like a semicolon is missing from the tupled struct definition. As it was defined, it produced the following compiler error:
```console
error: expected one of `;` or `where`, found `fn`
--> src/main.rs:10:1
|
3  | struct S(T)
|            - expected one of `;` or `where` here
```
=> Add semicolon to the tupled struct definition

content/_index.md
I poked around through a few different projects to try and track down why this had changed, but I couldn't come up with anything.
=> Fix link to rust book in `@ Bindings` section

content/_index.md
Just a stray "a". Keep up with the amazing work!
=> docs: Fix typo in the diagram for async code

content/_index.md
There is no "T : !Sized" kind syntax in Rust.  The correct writing is "T : ?Sized".
=> fix a wrong usage about unsized bound

content/_index.md
- `rustup doc` is shorter than `rustup docs`
- easier to remember as there is `cargo doc`
- the official help page uses `doc` not `docs`
=> Use `rustup doc`

content/_index.md, templates/shortcodes/rfc.html
I hope you don't mind that i submitted this as an RFC instead of as an issue, so please feel free to reject but I think it we should add a section on match ergonomics to the language sugar section. I'm not 100% happy with the explanation I came up with, I feel like there might be other links we can add, and we should maybe not call it match ergonomics because the sugar here applies to all patterns, not just match patterns, but its a start!
=> add section on match ergonomics to lang sugar

content/_index.md
Hey,
just added `cargo tree` to the list of cargo commands.
I wasn't sure about the ordering, please let me know.
Johannes
=> cargo: added tree sub-command

.github/workflows/generate_release.yml
Hi @ralfbiedert, as you commented here #112 the activity is listed by Github notification feature and it's per user configuration, you can disable notifications for releases in this repo.
Go to https://github.com/watching and choose `Custom`, then only check `Issues` and `Pull Requests`:
Once you changed that, you can merge this PR to restore the trigger on `master` and test if everything runs as you expect.
This closes #112
Thanks for the cheat sheet, great quality and awesome resource!
=> chore: generate release on master

content/_index.md
The build file should be at the root. In addition, cargo configuration can be added locally.
=> Fix Tooling Section

sass/_html.scss, static/index.js, templates/index.html
Currently, the page appearance (day or night) is determined by the class added by JavaScript, after the entire page is loaded.    This causes the page "blinks" before it gets dark when user prefers dark mode.  By this PR, the page first uses the preliminary background color based on system preference, so this issue is handled.
Currently, the pages shows on the day mode even if system prefers dark one.  The new code checks for the system preference if there is no value stored in LocalStorage, and selects appropriate theme.
=> Some improemenets on night mode

content/_index.md
This adds `while let`  to the pattern matching section (taking example from `if let` which is absent from the control flow section but reported in the pattern matching one).
The description is a compromise between conciseness and explaining; I might have erred on the conciseness side.
(BTW - thanks for this amazing resource!)
=> Adds `while let` to the pattern-matching section

content/_index.md
=> Fix unsafe function declaration syntax

content/_index.md
It is potentially surprising that `&expr` can have a different lifetime depending on whether or not `expr` is const-evaluable due to a special case in the borrow checker. Also, the fact that `&mut []` is allowed and has type `&'static mut [T]` was very unintuitive to me at first, especially because `&'static mut` references are rarely encountered in any other context.
=> Add rvalue promotion to "Language Sugar" table

content/_index.md
The current wording could be interpreted to mean that `mut` references and `*mut` raw pointers are "identical":
> References give safe access to other memory, raw pointers unsafe access. **The respective mut types are identical.**
I had a go at updating the wording to make it clearer.
=> updated the wording of the References & Pointers intro text

content/_index.md
I noticed `=> {}` is missing in some `match` arm examples. This PR fixes them.
=> Add missing `=> {}` in `match` arm examples

content/_index.md
Hello,
I think your cheat sheet is neat and very well thought out.
Happy to help with small omission I happened to notice - the behavior described [here](https://doc.rust-lang.org/reference/paths.html#path-qualifiers).
If you have better idea how to present this version difference, feel free to change it.
Cheers!
=> Add note about crate searching of global paths

content/_index.md
Some active reading, some opinions. This is more of a basis for discussion rather than a please-merge-as-is.
Notes:
- I write `Vec` is the type constructor, not `Vec<>`. Reason: You would say `f: bool -> bool`, not `f(): bool -> bool`.
- I reflowed my input for easier line referencing, but that can be undone before merging.
- `fn f(x: !) {}` is called _not very useful_, [that’s not true](https://de.wikipedia.org/wiki/Ex_falso_quodlibet)!
```rust
fn ex_falso<T>(x: !) -> T {
panic!("You proved falsehood exists, the universe will now deconstruct. I hope you’re happy")
}
fn testi_mc_testface() {
let always_ok: Result<(), !> = Ok(());
match always_ok {
Ok(_) => println!("ok"),
Err(e) => ex_falso(e), // Commenting this out yields a inexhaustive match
}
}
```
=> Various fixes and suggestions

content/_index.md
The Rust feature [`os_str_bytes`](https://github.com/rust-lang/rust/issues/111544) has been stabilized in 1.74.0 and we can use them to avoid `OsStrExt`, etc.
=> Update feature `os_str_bytes` in Rust 1.74.0
